site_name: MeshCreator
site_url: https://name-hw.github.io/MeshCreator
nav:
  - Home: index.md
  - Tutorials:
      tutorials/index.md
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  font:
    text: Noto Sans
  language: en
extra:
  version:
    provider: mike
    default: stable
    alias: true